spring.application.name=finangest
server.port=8081
server.servlet.context-path=/finangest

# Configurações de persistência e JDBC (Preparado para Nuvem)
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update